version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.63.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Build
          command: "cargo build"
      - run:
          name: Run Tests
          command: "cargo test"
      - run:
          name: Lint
          command: "cargo clippy"
      - run:
          name: Check Formatting
          command: "cargo fmt --all -- --check"

